### ISSUE TITLE
8. 프로필 페이지 구현

### ISSUE THREAD

**Issue by baekjs0123** [baekjs0123/Jasongram_211118#8]
# 1. 프로필 페이지 마크업

# 2. modal창 활용하기
- 이미지 태그를 감싸고 있는 a 태그를 클릭하면, modal창을 띄운다.
- [x] 모달창 띄워서 프로필 이미지 업로드 및 삭제 버튼 노출

# 3. 프로필 이미지 업로드 기능 구현
- [x] 프로필 이미지 업로드시 확장자명 체크 및 유효성 검사
- [x] 프로필 이미지 업로드 버튼에 현재 userId data 심기
- [x] 프로필 이미지 업로드 API

# 4. 프로필 이미지 삭제 기능 구현
- [x] 프로필 이미지 삭제 버튼에 현재 userId data 심기
- [x] 프로필 이미지 삭제 API
